name: Firebase Continuous Deployment

on:
    push:
        branches: [master]

jobs:
    firebase-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: '12'
            - run: yarn install
              env:
                  VUE_APP_FIREBASE_APIKEY: ${{ secrets.FIREBASE_APIKEY }}
                  VUE_APP_FIREBASE_AUTHDOMAIN: ${{ secrets.FIREBASE_AUTHDOMAIN }}
                  VUE_APP_FIREBASE_DATABASEURL: ${{ secrets.FIREBASE_DATABASEURL }}
                  VUE_APP_FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
                  VUE_APP_FIREBASE_STORAGEBUCKET: ${{ secrets.FIREBASE_STORAGEBUCKET }}
                  VUE_APP_FIREBASE_MESSAGINGSENDERID: ${{ secrets.FIREBASE_MESSAGINGSENDERID }}
                  VUE_APP_FIREBASE_APPID: ${{ secrets.FIREBASE_APPID }}
                  VUE_APP_FIREBASE_MEASUREMENTID: ${{ secrets.FIREBASE_MEASUREMENTID }}
            - run: yarn generate
            - uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
